[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/gin-contrib/zap"
  revision = "a4f331736217f34737505ce743f9d41efb41e0ab"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/metrics20/go-metrics20"
  revision = "717ed3a27bf9f8d2469e7ea5b36037a4793eee44"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.9.1"
